// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SchoolManagementService.Infrastructure.Persistence;

#nullable disable

namespace SchoolManagementService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CommandContext))]
    partial class CommandContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SchoolManagementService.Core.Domain.School", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("AreOccupied")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("GradingSystem")
                        .HasColumnType("bigint");

                    b.Property<string>("Img")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("OwnershipType")
                        .HasColumnType("integer");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("PostalCode")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Region")
                        .HasColumnType("integer");

                    b.Property<decimal>("RegisterCode")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("ShortName")
                        .HasColumnType("text");

                    b.Property<string>("SiteUrl")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("StudentsQuantity")
                        .HasColumnType("bigint");

                    b.Property<string>("TerritorialCommunity")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Img")
                        .IsUnique();

                    b.HasIndex("RegisterCode")
                        .IsUnique();

                    b.ToTable("Schools", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
