global using CourseService.Application.Common.DataContext;
global using CourseService.Domain.Entities;
global using CourseService.Domain.Enums.Lesson;
global using CourseService.Infrastructure.Persistence.EntityTypeConfigurations;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Serilog;
